### ISSUE TITLE
Замечания по коду

### ISSUE THREAD

**Issue by sergey-shambir** [AniSkyWorker/Fgame2.1#1]
Следует отрефакторить все объявления констант в начале файла `Fgame2.1.cpp`.
- Имена констант следует писать большими буквами через подчёркивание, например, "ball_radius" следует заменить на "BALL_RADIUS"
- На одно объявление переменной - одна строка. Строки вида `const int window_width = 800, window_heigth = 600;` следует либо разделить на две строки, либо заменить на `const Vector2i WINDOW_SIZE(800, 600)`, а у размера окна брать x и y.

**Comment by AniSkyWorker** [comment]
Исправил объявление и имена констант
